### PR TITLE
YouTube addition

### PR DESCRIPTION
**Pull request by WindowsMI**
i decided to do this because envy didn't have youtube

### CODE REVIEW

**Comment by DavidTDC3377** [comment]
This isn't YouTube..

**Comment by DavidTDC3377** [comment]
Couldn't you `iframe` the main YouTube page?

**Comment by OwnedByWuigi** [comment]
invidious is lighter, as youtube is a spaghetti of JS

**Comment by DavidTDC3377** [comment]
Oh I see.

**Comment by DavidTDC3377** [comment]
Reopening...

**Comment by OwnedByWuigi** [comment]
@WindowsMI Invidious refuses to connect after adding your Invidious code, is this simply another case of no iframe?

**Comment by OwnedByWuigi** [comment]
image

**Comment by DavidTDC3377** [comment]
Guessing no `iframe` as well.

**Comment by DavidTDC3377** [comment]
>  @WindowsMI Invidious refuses to connect after adding your Invidious code, is this simply another case of no iframe?

This is locked so only contributors can reply, I'll unlock it now.

**Comment by DavidTDC3377** [comment]
What do you mean? Isn't it just one website lol??

**Comment by DavidTDC3377** [comment]
Also it might not work.

**Comment by OwnedByWuigi** [comment]
no there a whole list of invidious instances at invidious.org

**Comment by OwnedByWuigi** [comment]
invidious.io*

**Comment by DavidTDC3377** [comment]
Do the other clients work @OwnedByWuigi? I see you commiting a bunch of different clients?

**Comment by DavidTDC3377** [comment]
Do the other clients work @OwnedByWuigi? I see you commiting a bunch of different clients?

**Comment by OwnedByWuigi** [comment]
only tested two, one is still deploying rn

**Comment by DavidTDC3377** [comment]
Oh I see lol

**Comment by WindowsMI** [comment]
@OwnedByWuigi https://github.com/iv-org/invidious/issues/3459#issuecomment-1333948056

**Pull request closed without merging**
