### PR TITLE
Formatted code

### PR DESCRIPTION
**Pull request by skywarspro15**

### CODE REVIEW

**Comment by datkat21** [comment]
LGTM!

**Review by OwnedByWuigi — APPROVED** [review]
ok pulling now :3

**Comment by DavidTDC3377** [comment]
one sec. resolving merge conflicts.

**Comment by DavidTDC3377** [comment]
I don't really see what you did with the code. You just added spaces to the `<br/>` tags and put lines of code in different places.

**Comment by datkat21** [comment]
You deleted my LGTM comment? Lol

**Comment by DavidTDC3377** [comment]
Closing as per @datkat21 msg...

**Pull request closed without merging**
